### ISSUE TITLE
Change b013 ADS8689RUM to ADS8689IRUM

### ISSUE THREAD

**Issue by Jearde** [skunkforce/things_on_edge#19]
Board: b013_ADC_differential_ADS868x
ADS8689RUM is not a chip which is available for purchase.
Either change the ADC to ADS8689IRUM or use ADS8689IPWR/ADS8685IPWR/ADS8681IPWR for compatibility with all variants.

**Comment by odinthenerd** [comment]
fixed in version 0.3
